package main

import "github.com/charmbracelet/lipgloss"

var (
	hintStyle        = lipgloss.NewStyle().Foreground(lipgloss.Color("244"))
	promptStyle      = lipgloss.NewStyle().Foreground(lipgloss.Color("35")).Bold(true)
	inputTextStyle   = lipgloss.NewStyle().Foreground(lipgloss.Color("252"))
	placeholderStyle = lipgloss.NewStyle().Foreground(lipgloss.Color("244"))
	cursorLineStyle  = lipgloss.NewStyle().Background(lipgloss.Color("236"))
	userLabelStyle   = lipgloss.NewStyle().Foreground(lipgloss.Color("245")).Bold(true)
	assistantLabel   = lipgloss.NewStyle().Foreground(lipgloss.Color("245")).Bold(true)
	systemLabel      = lipgloss.NewStyle().Foreground(lipgloss.Color("203")).Bold(true)
	toolLabelStyle   = lipgloss.NewStyle().Foreground(lipgloss.Color("81")).Bold(true)
	userBubble       = lipgloss.NewStyle().Background(lipgloss.Color("238")).Foreground(lipgloss.Color("255")).Padding(0, 1)
	assistantStyle   = lipgloss.NewStyle().Foreground(lipgloss.Color("250"))
	assistantPrefix  = lipgloss.NewStyle().Foreground(lipgloss.Color("239"))
	systemStyle      = lipgloss.NewStyle().Foreground(lipgloss.Color("203"))
	toolStyle        = lipgloss.NewStyle().Foreground(lipgloss.Color("81"))
	toolPrefix       = lipgloss.NewStyle().Foreground(lipgloss.Color("81"))
	codeBlockStyle   = lipgloss.NewStyle().Background(lipgloss.Color("235")).Foreground(lipgloss.Color("252"))
	codeFenceStyle   = lipgloss.NewStyle().Foreground(lipgloss.Color("241"))
	inlineCodeStyle  = lipgloss.NewStyle().Background(lipgloss.Color("235")).Foreground(lipgloss.Color("252"))
	boldStyle        = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("252"))
	heading1Style    = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("220"))
	heading2Style    = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("214"))
	heading3Style    = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("208"))
	listBulletStyle  = lipgloss.NewStyle().Foreground(lipgloss.Color("246"))
	quoteStyle       = lipgloss.NewStyle().Foreground(lipgloss.Color("244"))
	approvalBox      = lipgloss.NewStyle().Border(lipgloss.RoundedBorder()).BorderForeground(lipgloss.Color("208")).Padding(0, 1)
	approvalTitle    = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("214"))
	approvalHint     = lipgloss.NewStyle().Foreground(lipgloss.Color("244"))
	approvalOption   = lipgloss.NewStyle().Foreground(lipgloss.Color("245"))
	approvalActive   = lipgloss.NewStyle().Foreground(lipgloss.Color("214")).Bold(true)
	rateLimitStyle   = lipgloss.NewStyle().Foreground(lipgloss.Color("214"))
)
